baseURL = "https://hazulifidastian.github.io/"
languageCode = "id-id"
title = "Hazuli Fidastian"

theme = "hugo-mood-theme"
disableKinds = []
googleAnalytics = "UA-9380146-9"
disqusShortname = "hazulifidastian"
enableEmoji = true

[Author]
  name = "Hazuli"
  bio = "Pengembang perangkat lunak, berkerja lepas (freelance) di Jakarta."

[[menu.main]]
    identifier = "about"
    name = "Me"
    url = "/about/"
    weight = 3

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
    mainSections = []

    description = "Halo!, saya Hazuli Fidastian. Saya bekerja lepas sebagai pengembang aplikasi di Jakarta."

    defaultContentLanguage = "id"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 80
    height = 80
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "monokailight"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2

[permalinks]
    apps = "/app/:filename"
    blog = "/blog/:filename"
    notes = "/blog/:filename"
